language: ruby
sudo: required

services:
- docker

script:
  - docker run -it --rm -v $PWD:/srv/jekyll -eJEKYLL_UID=$UID jekyll/builder:pages jekyll build --config _config.yml,_prod.yml
  - docker run -it  --rm -v $(pwd)/_site:/site -it jekyll/builder:pages /usr/gem/bin/htmlproofer /site --disable-external

before_deploy:
  - tar -zcvf ${TRAVIS_REPO_SLUG#*/}.tar.gz -C _site ./
  - sha256sum ${TRAVIS_REPO_SLUG#*/}.tar.gz > SHASUMS

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ${TRAVIS_REPO_SLUG#*/}.tar.gz
    - SHASUMS
  skip_cleanup: true
  on:
    tags: true
